#!/bin/bash
#
# jxproxy — macOS / Linux Installer
#
# Installs: jxproxy CLI binary, jxproxy proxy server binary, launcher script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/your-org/jxproxy/main/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/your-org/jxproxy/main/install.sh | bash -s -- --min
#   curl -fsSL https://raw.githubusercontent.com/your-org/jxproxy/main/install.sh | bash -s -- --provider=openrouter
#
# Flags:
#   --min           Shallow clone (faster, smaller)
#   --provider=X    Set default provider (direct, openrouter, openai, local)
#   --bin-dir=DIR   Install binaries to DIR (default: ~/.local/bin)
#   --no-build      Skip building, only fetch and install scripts
#

set -euo pipefail

# --- Config ---
REPO="https://github.com/your-org/jxproxy.git"
CLONE_DIR="${HOME}/.jxproxy-source"
BIN_DIR="${HOME}/.local/bin"
DATA_DIR="${HOME}/.jxproxy"
PROVIDER="direct"
MIN_CLONE=""
NO_BUILD=""

# Parse arguments
for arg in "$@"; do
  case "$arg" in
    --min) MIN_CLONE="--min" ;;
    --no-build) NO_BUILD="1" ;;
    --provider=*) PROVIDER="${arg#*=}" ;;
    --bin-dir=*) BIN_DIR="${arg#*=}" ;;
    --help|-h)
      echo "jxproxy installer — macOS/Linux"
      echo ""
      echo "  --min           Shallow clone (faster)"
      echo "  --provider=X    Default provider: direct, openrouter, openai, local"
      echo "  --bin-dir=DIR   Install location (default: ~/.local/bin)"
      echo "  --no-build      Fetch only, don't compile"
      exit 0
      ;;
  esac
done

# --- Platform Detection ---
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Darwin) PLATFORM="macos" ;;
  Linux)  PLATFORM="linux" ;;
  *)
    echo "Unsupported OS: $OS — macOS or Linux required."
    echo "For Windows, use installers/install.ps1"
    echo "For Android/Termux, use installers/install-android.sh"
    exit 1
    ;;
esac

case "$ARCH" in
  x86_64|amd64) ARCH_BITS="x64" ;;
  aarch64|arm64) ARCH_BITS="arm64" ;;
  *)
    echo "Unsupported architecture: $ARCH"
    exit 1
    ;;
esac

echo ""
echo "  jxproxy Installer"
echo "  ================="
echo "  Platform: $PLATFORM ($ARCH_BITS)"
echo "  Bin dir:  $BIN_DIR"
echo "  Data dir: $DATA_DIR"
echo ""

# --- Dependencies ---

echo "[1/5] Checking dependencies..."

if ! command -v git &>/dev/null; then
  echo "  Installing git..."
  if [ "$PLATFORM" = "macos" ]; then
    xcode-select --install 2>/dev/null || true
  else
    echo "  Please install git: apt-get install git (Debian) or yum install git (RHEL)"
    exit 1
  fi
fi

if ! command -v bun &>/dev/null; then
  echo "  Installing Bun runtime..."
  curl -fsSL https://bun.sh/install | bash
  export BUN_INSTALL="${HOME}/.bun"
  export PATH="${BUN_INSTALL}/bin:${PATH}"
fi

BUN_VER=$(bun --version 2>/dev/null || echo "0")
echo "  ✓ bun ${BUN_VER}"
echo "  ✓ git"
echo ""

# --- Clone Repository ---

echo "[2/5] Cloning jxproxy..."

if [ -d "$CLONE_DIR" ]; then
  echo "  Updating existing clone..."
  cd "$CLONE_DIR"
  git pull --ff-only
else
  if [ -n "$MIN_CLONE" ]; then
    git clone --depth 1 "$REPO" "$CLONE_DIR"
  else
    git clone "$REPO" "$CLONE_DIR"
  fi
  cd "$CLONE_DIR"
fi

echo ""

# --- Bootstrap ---

echo "[3/5] Bootstrapping build environment..."
cd "$CLONE_DIR"

if [ -d "src" ] && [ -f "src/entrypoints/cli.tsx" ]; then
  echo "  ✓ Source already present"
else
  bash scripts/bootstrap.sh ${MIN_CLONE:+"--min"}
fi

echo ""

# --- Build ---

echo "[4/5] Building jxproxy..."

mkdir -p "$BIN_DIR" "$DATA_DIR"

if [ -z "$NO_BUILD" ]; then
  bun run build 2>&1 | tail -5
  echo "  ✓ CLI binary built"

  bun run build:proxy 2>&1 | tail -5 || {
    echo "  ⚠ Proxy binary build skipped (optional)"
  }
else
  echo "  Skipping build (--no-build flag)"
fi

# --- Install ---

echo "[5/5] Installing..."

# Copy binaries
if [ -f "dist/jxproxy" ]; then
  cp "dist/jxproxy" "$BIN_DIR/jxproxy"
  chmod 0o755 "$BIN_DIR/jxproxy"
  echo "  ✓ Installed: $BIN_DIR/jxproxy"
fi

if [ -f "dist/jxproxy-proxy" ]; then
  cp "dist/jxproxy-proxy" "$BIN_DIR/jxproxy-proxy"
  chmod 0o755 "$BIN_DIR/jxproxy-proxy"
  echo "  ✓ Installed: $BIN_DIR/jxproxy-proxy"
fi

# Install launcher
cp "scripts/jxproxy-launcher.sh" "$BIN_DIR/jxproxy"
chmod 0o755 "$BIN_DIR/jxproxy"
echo "  ✓ Launcher: $BIN_DIR/jxproxy"

# Create default config
CONFIG_FILE="$DATA_DIR/config.env"
if [ ! -f "$CONFIG_FILE" ]; then
  cat > "$CONFIG_FILE" << 'CONFIGEOF'
# jxproxy configuration
# Generated by installer — edit to customize

JXPROXY_PORT=2099
JXPROXY_PROVIDER=direct
MODEL=claude-sonnet-5-20251001
ENABLE_MODEL_THINKING=true

# Uncomment and set your provider keys:
# ANTHROPIC_API_KEY=sk-ant-...
# OPENROUTER_API_KEY=sk-or-...
# OPENAI_API_KEY=sk-...
CONFIGEOF
  echo "  ✓ Config: $CONFIG_FILE"
fi

# Add to PATH if needed
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  SHELL_CONFIG=""
  case "${SHELL:-}" in
    */bash) SHELL_CONFIG="$HOME/.bashrc" ;;
    */zsh)  SHELL_CONFIG="$HOME/.zshrc" ;;
    */fish) SHELL_CONFIG="$HOME/.config/fish/config.fish" ;;
  esac
  if [ -n "$SHELL_CONFIG" ] && [ -f "$SHELL_CONFIG" ]; then
    echo "export PATH=\"\$PATH:$BIN_DIR\"" >> "$SHELL_CONFIG"
    echo "  ✓ Added $BIN_DIR to PATH in $SHELL_CONFIG"
    echo "    Restart your shell or run: export PATH=\"\$PATH:$BIN_DIR\""
  fi
fi

echo ""

# --- Done ---

echo "  ✓ jxproxy installed!"
echo ""
echo "  Quick start:"
echo "    jxproxy             # Launch proxy + CLI"
echo "    jxproxy -- --help   # CLI help"
echo ""
echo "  Config:  $CONFIG_FILE"
echo "  Binaries: $BIN_DIR/jxproxy"
echo "  Logs:    $DATA_DIR/proxy.log"
echo ""
